variables:
  DOCKER_DRIVER: overlay2
  MONGO_URI: mongodb://127.0.0.1/stub
  SECRET: thisismyappsecret
  DEBUG: true
  TEST: true

services:
  - mongo:latest

stages:
  - test

run_tests:
  stage: tests
  image: node:10-alpine
  tags:
    - docker
  script:
    - npm ci
    - npm test
