variables:
  DOCKER_DRIVER: overlay2

services:
  - mongo:latest

stages:
  - test

run_tests:
  stage: test
  image: node:10-alpine
  variables:
    MONGO_URI: "mongodb://127.0.0.1/stub"
    SECRET: "thisismyappsecret"
    DEBUG: "true"
    TEST: "true"
  tags:
    - docker
  script:
    - npm ci
    - npm test
