language: node_js
node_js:
  - "node"
env:
  global:
    - MONGO_URI_LOCAL=mongodb://127.0.0.1/ongoingness
    - SECRET=thisismyappsecret
    - DEBUG=true
    - TEST=true
    - LOCAL=true
    - DB_TYPE=MONGO
services: mongodb
before_script:
  - tsc
