version: '2'
services:
  web:
    build: .
    ports:
    - 3000:3000
    volumes:
    - "./web:/app/web"
    - "./app.ts:/app/app.ts"
    - "./.env:/app/.env"
    - "./dist:/app/dist"
    - "./test:/app/test"
    environment:
      MONGO_URI: mongodb://46.101.47.18/ongoingness