version: '2'
services:
  web:
      build: .
      ports:
      - 3000:3000
      volumes:
      - "./web:/app/web"
      - "./app.ts:/app/app.ts"
      - "./.env:/app/.env"
      - "./dist:/app/dist"
      - "./test:/app/test"
      depends_on:
        - mongo
      links:
        - mongo
      environment:
        MONGO_URI: mongodb://mongo/ongoingness
  mongo:
    # image: mongo
    build: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'data:/data/db'

volumes:
  data:
